ALTER SERVER ROLE [sysadmin] ADD MEMBER [DESKTOP-TO892BU\Tommy];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

